version: "3.8"

services:
  backend:
    container_name: arbora-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    env_file:
      - .env
    restart: unless-stopped
