version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5100:5100"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
